name: build workflows

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-linux:
    name: compile linux
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: install packages
        run: sudo apt-get update && sudo apt-get install -y build-essential autoconf zip unzip openjdk-21-jdk dos2unix libasound2-dev libcups2-dev libfontconfig1-dev libx11-dev libxext-dev libxrender-dev libxrandr-dev libxtst-dev libxt-dev
      
      - name: build linux
        run: |
          dos2unix build.sh
          chmod +x build.sh
          ./build.sh
      
      - name: compress output
        run: |
          cd jdk-src/build/*/images/jdk
          zip -r ../../../../../TachyonVM-Linux-x64.zip .
      
      - name: upload linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: TachyonVM-Linux
          path: TachyonVM-Linux-x64.zip

  build-windows:
    name: compile windows
    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: setup msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            autoconf
            make
            zip
            unzip
            tar
            git
            dos2unix
      
      - name: setup boot jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: build windows
        shell: msys2 {0}
        run: |
          dos2unix build.sh
          chmod +x build.sh
          ./build.sh || echo "Windows build failed, but we continue to get logs"
      
      - name: compress output
        shell: pwsh
        run: |
          if (Test-Path "jdk-src\build\*\images\jdk\*") {
            Compress-Archive -Path "jdk-src\build\*\images\jdk\*" -DestinationPath "TachyonVM-Windows-x64.zip"
          } else {
            Write-Host "JDK build directory not found, skipping compression."
          }
      
      - name: upload windows artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: TachyonVM-Windows
          path: TachyonVM-Windows-x64.zip
