name: build windows

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup boot jdk
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: setup cygwin
        uses: egor-tensin/setup-cygwin@v4
        with:
          packages: autoconf make zip unzip wget tar grep sed dos2unix ca-certificates file

      - name: setup msvc
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: compile jdk
        shell: C:\tools\cygwin\bin\bash.exe --norc -eo pipefail -o igncr '{0}'
        env:
          BOOT_JDK: ${{ env.JAVA_HOME }}
        run: |
          cd "$GITHUB_WORKSPACE"
          dos2unix build-win.sh || true
          bash build-win.sh

      - name: compile inno setup installer
        shell: cmd
        run: |
          "C:\Program Files (x86)\Inno Setup 6\iscc.exe" tachyonvm.iss

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TachyonVM-Server-Windows-Installer
          path: Output/TachyonVM-Server-Installer-Win64.exe
