name: Build TachyonVM (Windows)

on:
  workflow_dispatch: # Allows you to manually trigger the build from GitHub UI

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Boot JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Setup Cygwin
        uses: egor-tensin/setup-cygwin@v4
        with:
          packages: autoconf make zip unzip wget tar grep sed dos2unix ca-certificates file

      - name: Setup Visual Studio Environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build Custom JDK
        shell: C:\tools\cygwin\bin\bash.exe --norc -eo pipefail -o igncr '{0}'
        env:
          BOOT_JDK: ${{ env.JAVA_HOME }}
        run: |
          cd "$GITHUB_WORKSPACE"
          dos2unix build-win.sh || true
          bash build-win.sh

      - name: Compile Installer (.exe)
        shell: cmd
        run: |
          "C:\Program Files (x86)\Inno Setup 6\iscc.exe" tachyonvm.iss

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TachyonVM-Installer-Win64
          path: Output/TachyonVM-Installer-Win64.exe
